import os
import sys
import hashlib
import asyncio
from telethon import TelegramClient
from telethon.tl.types import Channel, Chat, DocumentAttributeFilename
from telethon.tl.functions.channels import GetForumTopicsRequest
from collections import defaultdict

# --- CONFIGURATION ---
SESSION_NAME = 'telegram_cleaner'
PARTIAL_HASH_THRESHOLD_MB = 20
PARTIAL_HASH_CHUNK_SIZE = 1024 * 1024
TEMP_FILE_PATH = 'temp_download_for_hash'
# ---------------------

def clean_generated_files(clean_session=True):
    """Deletes files generated by this script."""
    print("🧹 Starting cleanup...")
    files_to_clean = [TEMP_FILE_PATH + ".tmp"]
    if clean_session:
        files_to_clean.append(SESSION_NAME + ".session")

    cleaned_count = 0
    for file_path in files_to_clean:
        if os.path.exists(file_path):
            try:
                os.remove(file_path)
                print(f"  - Deleted: {file_path}")
                cleaned_count += 1
            except OSError as e:
                print(f"  - Error deleting {file_path}: {e}")
    
    if cleaned_count == 0:
        print("✨ No generated files found to clean.")
    else:
        print("✅ Cleanup complete.")


def get_file_hash(file_path):
    """Calculates the SHA256 hash of a file."""
    sha256 = hashlib.sha256()
    with open(file_path, 'rb') as f:
        while True:
            data = f.read(65536)
            if not data:
                break
            sha256.update(data)
    return sha256.hexdigest()

async def get_full_hash(client, media, temp_path):
    path = await client.download_media(media, file=temp_path)
    if not path:
        return None
    file_hash = get_file_hash(path)
    os.remove(path)
    return file_hash

async def get_partial_hash(client, media):
    sha256 = hashlib.sha256()
    async for chunk in client.iter_download(media, request_size=PARTIAL_HASH_CHUNK_SIZE):
        sha256.update(chunk)
        break
    return sha256.hexdigest()


async def select_topic(client, group_entity):
    """If the group is a forum, lists topics and asks for selection."""
    if not isinstance(group_entity, Channel) or not group_entity.forum:
        return None

    print(f"\n'{group_entity.title}' has Topics enabled.")
    
    try:
        result = await client(GetForumTopicsRequest(channel=group_entity, offset_date=None, offset_id=0, offset_topic=0, limit=100))
        topics = result.topics
    except Exception as e:
        print(f"Could not fetch topics: {e}")
        return 0

    if not topics:
        print("No topics found in this group. Scanning the entire group.")
        return 0

    print("Please select a topic to scan, or scan the entire group:")
    print("  0: ✨ Scan Entire Group (All Topics)")
    for i, topic in enumerate(topics):
        print(f"  {i + 1}: {topic.title}")
    
    while True:
        try:
            choice = int(input("\n➡️  Enter your choice: "))
            if 0 <= choice <= len(topics):
                return topics[choice - 1].id if choice > 0 else 0
            else:
                print("Invalid number. Please try again.")
        except ValueError:
            print("Invalid input. Please enter a number.")


async def find_and_delete_duplicates(client, group_entity, topic_id):
    """Finds and deletes duplicate files in the selected entity."""
    scan_target = group_entity.title
    scan_args = {'entity': group_entity}
    if topic_id:
        scan_args['reply_to'] = topic_id
        scan_target += f" (Topic ID: {topic_id})"
    
    print(f"\n🔍 Starting Pass 1: Indexing files in '{scan_target}'...")
    
    files_by_size = defaultdict(list)
    message_count = 0
    async for message in client.iter_messages(**scan_args):
        message_count += 1
        if message_count % 200 == 0:
            print(f"  ...scanned {message_count} messages")
        
        media = message.media
        file_obj = getattr(media, 'document', getattr(media, 'photo', None))
        if not file_obj or not hasattr(file_obj, 'size'):
            continue
            
        file_info = {
            'id': message.id,
            'date': message.date,
            'size': file_obj.size,
            'name': next((attr.file_name for attr in file_obj.attributes if isinstance(attr, DocumentAttributeFilename)), 'N/A'),
            'media': media
        }
        files_by_size[file_obj.size].append(file_info)

    print(f"✅ Pass 1 Complete. Scanned {message_count} messages.")

    potential_duplicates = {size: files for size, files in files_by_size.items() if len(files) > 1}

    if not potential_duplicates:
        print("\n🎉 No potential duplicates found (files with same size). All good!")
        return

    print(f"\n🔍 Starting Pass 2: Verifying {sum(len(files) for files in potential_duplicates.values())} potential duplicates by content hashing...")

    hashes = {}
    duplicates_to_delete = []
    
    temp_file_for_hashing = TEMP_FILE_PATH + ".tmp"
    threshold_bytes = PARTIAL_HASH_THRESHOLD_MB * 1024 * 1024

    for size, files in potential_duplicates.items():
        print(f"  ...verifying {len(files)} files of size {size / 1024 / 1024:.2f} MB")
        for file_info in files:
            try:
                file_hash = None
                if size > threshold_bytes:
                    file_hash = await get_partial_hash(client, file_info['media'])
                else:
                    file_hash = await get_full_hash(client, file_info['media'], temp_file_for_hashing)
                
                if not file_hash:
                    continue

                original_file = hashes.get(file_hash)
                if not original_file:
                    hashes[file_hash] = file_info
                else:
                    if file_info['date'] > original_file['date']:
                        duplicates_to_delete.append(file_info)
                    else:
                        duplicates_to_delete.append(original_file)
                        hashes[file_hash] = file_info
            
            except Exception as e:
                print(f"  ⚠️  Could not process message {file_info['id']}: {e}")
                continue

    if not duplicates_to_delete:
        print("\n🎉 Verification complete. No true duplicates found!")
        return
    
    duplicates_to_delete.sort(key=lambda x: x['date'], reverse=True)
    
    print("\n🚨 Found the following duplicate files to delete:")
    for file_info in duplicates_to_delete:
        print(f"  - File '{file_info['name']}' (Uploaded: {file_info['date'].strftime('%Y-%m-%d')}) is a duplicate.")

    print(f"\nTotal duplicates to delete: {len(duplicates_to_delete)}")
    
    confirm = input("➡️  Do you want to delete all these files? (yes/no): ").lower()
    
    if confirm == 'yes':
        print("\nDeleting files...")
        deleted_count = 0
        message_ids_to_delete = [f['id'] for f in duplicates_to_delete]
        
        for i in range(0, len(message_ids_to_delete), 100):
            chunk = message_ids_to_delete[i:i+100]
            await client.delete_messages(group_entity, chunk)
            deleted_count += len(chunk)

        print(f"\n✅ Successfully deleted {deleted_count} duplicate files.")
    else:
        print("\nAborted. No files were deleted.")


async def main():
    """Main function to run the script."""
    print("--- Telegram Duplicate File Cleaner ---")
    print("You can get your API credentials from my.telegram.org under 'API development tools'.")
    print("---------------------------------------")

    while True:
        try:
            api_id = int(input("Please enter your API ID: "))
            break
        except ValueError:
            print("❌ Invalid input. The API ID must be a number.")

    api_hash = input("Please enter your API Hash: ")

    async with TelegramClient(SESSION_NAME, api_id, api_hash) as client:
        print("\n🚀 Login successful. Script starting...")

        group_link = input("➡️  Please enter the group link (e.g., t.me/groupname or https://t.me/+...): ")
        
        try:
            group = await client.get_entity(group_link)
            print(f"✅ Successfully found group: '{group.title}'")

            has_permission = group.creator or (group.admin_rights and group.admin_rights.delete_messages)
            if not has_permission:
                print("❌ You do not have permission to delete messages in this group.")
                return
            print("✅ You have the required permissions.")

        except (ValueError, TypeError):
            print(f"❌ Could not find the group '{group_link}'. Please check the link and make sure you are a member.")
            return
        except Exception as e:
            print(f"❌ An error occurred: {e}")
            return
        
        topic_id = await select_topic(client, group)
        if topic_id is None:
            topic_id = 0 

        await find_and_delete_duplicates(client, group, topic_id if topic_id != 0 else None)


if __name__ == "__main__":
    # Handle --clean flag first
    if len(sys.argv) > 1 and sys.argv[1].lower() == '--clean':
        clean_generated_files(clean_session=True)
        sys.exit(0)

    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        # On Ctrl+C, clean up temp files but not the session, then exit gracefully
        print("\n\n👋 Script interrupted by user. Cleaning up and exiting...")
        clean_generated_files(clean_session=False) 
        sys.exit(0)
    except Exception as e:
        # On any other error, print it and clean up temp files
        print(f"\n❌ An unexpected error occurred: {e}")
        clean_generated_files(clean_session=False)
        sys.exit(1)